DROP TABLE IF EXISTS OURKIDS.COMPLAINTS;
DROP TABLE IF EXISTS OURKIDS.USER;

CREATE TABLE OURKIDS.COMPLAINT(
    ID              BIGINT          NOT NULL UNIQUE AUTO_INCREMENT, 
    NAME            VARCHAR(255)    NOT NULL,
    DESCRIPTION     VARCHAR(255)    NOT NULL,
    CONTENT         VARCHAR(255)    NOT NULL,
    PERSON          VARCHAR(255)    NOT NULL,
    DAY             VARCHAR(255)    NOT NULL,
    PROBLEM         VARCHAR(255)    NOT NULL,
    REQUIREMENT     VARCHAR(255)    NOT NULL,
    FATHERS         INTEGER         NOT NULL,

    CONSTRAINT PK_COMPLAINT PRIMARY KEY (ID)    
);

CREATE TABLE OURKIDS.USER(
    ID              BIGINT          NOT NULL UNIQUE AUTO_INCREMENT, 
    USERNAME        VARCHAR(255)    NOT NULL UNIQUE,
    EMAIL           VARCHAR(255)    NOT NULL,
    STATUS          BIT             NOT NULL DEFAULT 0,
    PASSWORD        VARCHAR(255),

    CONSTRAINT PK_USER PRIMARY KEY (ID)
);